package tn.esprit.services;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.*;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

/**
 * Integration tests for the Paymee Payment service.
 *
 * NOTE: These tests perform real HTTP calls to the Paymee SANDBOX.
 *       They require an internet connection and a valid sandbox API key.
 *       The sandbox URL is: https://sandbox.paymee.tn/api/v2/payments/create
 *
 * Test cases covered:
 *  1. createPayment_validData_returnsSuccess      – happy path with all required fields
 *  2. createPayment_autoGeneratedOrderId          – order_id auto-generated via timestamp
 *  3. createPayment_debitTransaction              – DEBIT type with correct amount
 *  4. createPayment_zeroAmount_returnsApiError    – edge case: amount = 0 (API should reject)
 *  5. createPayment_capturesPaymentUrl            – verifies payment_url is present in response
 *  6. createPayment_responseIsValidJson           – verifies the response body is valid JSON
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class PaymentTest {

    private static final ObjectMapper mapper = new ObjectMapper();

    // Capture stdout to inspect what Payment.createPayment prints
    private ByteArrayOutputStream capturedOut;
    private PrintStream originalOut;

    @BeforeEach
    void captureOutput() {
        capturedOut  = new ByteArrayOutputStream();
        originalOut  = System.out;
        System.setOut(new PrintStream(capturedOut));
    }

    @AfterEach
    void restoreOutput() {
        System.setOut(originalOut);
        // Print captured output so Maven surefire shows it in the test report
        System.out.println(capturedOut);
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  HELPER
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Calls Payment.createPayment and returns the raw JSON response body
     * by parsing the captured stdout (which contains "--- Formatted Response ---").
     */
    private String callAndCapture(double amount, String note,
                                  String firstName, String lastName,
                                  String email, String phone,
                                  String orderId) throws Exception {
        Payment.createPayment(
            amount, note, firstName, lastName,
            email, phone,
            "https://app.fintech.tn/payment/success",
            "https://app.fintech.tn/payment/cancel",
            "https://iridaceous-misty-vivaciously.ngrok-free.dev/webhook/paymee",
            orderId
        );
        String output = capturedOut.toString();

        // Extract the JSON part that comes after "--- Formatted Response ---"
        String marker = "--- Formatted Response ---";
        int idx = output.indexOf(marker);
        if (idx < 0) return output.trim(); // fallback: return whole output
        return output.substring(idx + marker.length()).trim();
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  TEST 1 – Happy path
    // ─────────────────────────────────────────────────────────────────────────
    @Test
    @Order(1)
    @DisplayName("1. Valid payment data → API responds with status 200 and status:true")
    void createPayment_validData_returnsSuccess() throws Exception {
        String orderId = "TEST-" + System.currentTimeMillis();

        String json = callAndCapture(
            100.0, "Test payment from unit test",
            "Mohamed", "Tlili",
            "mohamedtlili@example.com", "+21612345678",
            orderId
        );

        System.setOut(originalOut);
        System.out.println("[TEST 1] Response:\n" + json);

        // Verify the output is parseable JSON
        JsonNode root = mapper.readTree(json);
        Assertions.assertNotNull(root, "Response JSON should not be null");

        // Paymee sandbox wraps in {"status":true/false, "data":{...}}
        if (root.has("status")) {
            System.out.println("[TEST 1] status field = " + root.get("status").asText());
            // Sandbox may return false for certain demo keys — we just assert it responded
            Assertions.assertNotNull(root.get("status"), "Response must contain a 'status' field");
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  TEST 2 – Auto-generated order ID
    // ─────────────────────────────────────────────────────────────────────────
    @Test
    @Order(2)
    @DisplayName("2. Auto-generated order_id (ORD-timestamp) is accepted by the API")
    void createPayment_autoGeneratedOrderId() throws Exception {
        String orderId = "ORD-" + System.currentTimeMillis();

        String json = callAndCapture(
            250.500, "Insurance premium payment",
            "Amine", "Ben Salem",
            "amine@example.com", "+21698765432",
            orderId
        );

        System.setOut(originalOut);
        System.out.println("[TEST 2] Response:\n" + json);

        JsonNode root = mapper.readTree(json);
        Assertions.assertNotNull(root, "Response should be valid JSON for auto-generated order ID");
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  TEST 3 – Debit transaction
    // ─────────────────────────────────────────────────────────────────────────
    @Test
    @Order(3)
    @DisplayName("3. DEBIT type transaction with loan repayment note")
    void createPayment_debitTransaction() throws Exception {
        String orderId = "LOAN-" + System.currentTimeMillis();

        String json = callAndCapture(
            1500.0, "Monthly loan repayment – Loan #42",
            "Sami", "Hamdi",
            "sami.hamdi@example.com", "+21654321098",
            orderId
        );

        System.setOut(originalOut);
        System.out.println("[TEST 3] Response:\n" + json);

        JsonNode root = mapper.readTree(json);
        Assertions.assertNotNull(root, "Response should be valid JSON for debit transaction");
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  TEST 4 – payment_url is present in a successful response
    // ─────────────────────────────────────────────────────────────────────────
    @Test
    @Order(4)
    @DisplayName("4. Successful response contains payment_url inside data object")
    void createPayment_capturesPaymentUrl() throws Exception {
        String orderId = "URL-TEST-" + System.currentTimeMillis();

        String json = callAndCapture(
            75.0, "Test – checking payment URL",
            "Leila", "Mansouri",
            "leila@example.com", "+21622334455",
            orderId
        );

        System.setOut(originalOut);
        System.out.println("[TEST 4] Response:\n" + json);

        JsonNode root = mapper.readTree(json);
        Assertions.assertNotNull(root, "Response should be valid JSON");

        // If API call succeeded, data.payment_url should be present
        if (root.has("status") && root.get("status").asBoolean()) {
            JsonNode data = root.get("data");
            Assertions.assertNotNull(data, "data node should be present on success");
            Assertions.assertTrue(data.has("payment_url") || data.has("token"),
                    "Successful response should contain payment_url or token");
            if (data.has("payment_url")) {
                String paymentUrl = data.get("payment_url").asText();
                System.out.println("[TEST 4] Payment URL: " + paymentUrl);
                Assertions.assertTrue(paymentUrl.startsWith("http"),
                        "payment_url should start with http");
            }
        } else {
            System.out.println("[TEST 4] API returned status:false – skipping payment_url check");
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  TEST 5 – Response is always valid JSON regardless of outcome
    // ─────────────────────────────────────────────────────────────────────────
    @Test
    @Order(5)
    @DisplayName("5. API always returns valid JSON (even for error cases)")
    void createPayment_responseIsValidJson() throws Exception {
        String orderId = "JSON-CHECK-" + System.currentTimeMillis();

        // Use a minimal valid call
        String json = callAndCapture(
            50.0, "JSON validity check",
            "Test", "User",
            "test@test.com", "+21600000000",
            orderId
        );

        System.setOut(originalOut);
        System.out.println("[TEST 5] Response:\n" + json);

        // Must parse without throwing
        Assertions.assertDoesNotThrow(() -> mapper.readTree(json),
                "Response body must always be valid JSON");

        JsonNode root = mapper.readTree(json);
        Assertions.assertTrue(root.isObject() || root.isArray(),
                "Response must be a JSON object or array");
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  TEST 6 – Minimum amount boundary
    // ─────────────────────────────────────────────────────────────────────────
    @Test
    @Order(6)
    @DisplayName("6. Minimum positive amount (0.001 TND) is sent without throwing an exception")
    void createPayment_minimumAmount_doesNotThrow() {
        String orderId = "MIN-AMT-" + System.currentTimeMillis();

        // Just verify no exception is thrown from our side (API may reject, that's fine)
        Assertions.assertDoesNotThrow(() ->
            callAndCapture(
                0.001, "Minimum amount test",
                "Min", "Test",
                "min@test.com", "+21600000001",
                orderId
            ),
            "Payment.createPayment should not throw a Java exception for any positive amount"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  TEST 7 – Large amount
    // ─────────────────────────────────────────────────────────────────────────
    @Test
    @Order(7)
    @DisplayName("7. Large amount (100,000 TND) is sent without throwing an exception")
    void createPayment_largeAmount_doesNotThrow() {
        String orderId = "BIG-AMT-" + System.currentTimeMillis();

        Assertions.assertDoesNotThrow(() ->
            callAndCapture(
                100_000.0, "Large asset insurance payment",
                "Karim", "Oueslati",
                "karim@example.com", "+21699887766",
                orderId
            ),
            "Payment.createPayment should not throw for a large amount"
        );
    }
}

